// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportManager.Data;

#nullable disable

namespace SportManager.Data.Migrations
{
    [DbContext(typeof(SportManagerDBContext))]
    partial class SportManagerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SportManager.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("SportManager.Models.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Blessure")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Endurance")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Poste")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Technique")
                        .HasColumnType("int");

                    b.Property<int>("Vitesse")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("SportManager.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeuxiemeEquipeId")
                        .HasColumnType("int");

                    b.Property<int>("PremiereEquipeId")
                        .HasColumnType("int");

                    b.Property<int>("ScoreDeuxiemeEquipe")
                        .HasColumnType("int");

                    b.Property<int>("ScorePremiereEquipe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeuxiemeEquipeId");

                    b.HasIndex("PremiereEquipeId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("SportManager.Models.Match", b =>
                {
                    b.HasOne("SportManager.Models.Equipe", "DeuxiemeEquipe")
                        .WithMany()
                        .HasForeignKey("DeuxiemeEquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportManager.Models.Equipe", "PremiereEquipe")
                        .WithMany()
                        .HasForeignKey("PremiereEquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeuxiemeEquipe");

                    b.Navigation("PremiereEquipe");
                });
#pragma warning restore 612, 618
        }
    }
}
